apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-init
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  10-create-db.sql: |
    CREATE DATABASE report;
    CREATE DATABASE costrict_stat;
