stat_database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: "1"
  dbname: costrict_stat
  sslmode: disable

model_prices:
  GLM-4.7:
    in_price: 0.5
    out_price: 1.0
  GLM-4.7-Zhipu:
    in_price: 0.5
    out_price: 1.0
  GLM-5:
    in_price: 1.0
    out_price: 2.0
  GLM-5.1-Zhipu:
    in_price: 1.0
    out_price: 2.0
  Kimi-K2.5:
    in_price: 1.0
    out_price: 2.0
  MiniMax-M2.5:
    in_price: 0.5
    out_price: 1.0
  MiniMax-M2.5-Local:
    in_price: 0.5
    out_price: 1.0
  Kimi-K2.5-Moonshot:
    in_price: 1.0
    out_price: 2.0
  MiniMax-M2.7:
    in_price: 0.5
    out_price: 1.0
  MiniMax-M2.7-Local:
    in_price: 0.5
    out_price: 1.0
  MiniMax-M2.1:
    in_price: 0.5
    out_price: 1.0
  Qwen-2.5-VL:
    in_price: 0.5
    out_price: 1.0
  Auto:
    in_price: 0.5
    out_price: 1.0
  default:
    in_price: 0.5
    out_price: 1.0

ai_estimation:
  enabled: true
  api_key: "c0bebb770966452d9c415863d59c5161.alDVcnduh2Dgy3dN"
  base_url: "https://open.bigmodel.cn/api/anthropic"
  model: "claude-3-5-sonnet-20241022"
  timeout_ms: 300000
  http_proxy: ""

algo_estimation:
  max_input_chars: 300000    # 最大输入字符数
  max_ratio: 50              # 工作量的最大倍数
  max_factor: 1.0            # 最大的加权系数
  min_factor: 0.2            # 最小的加权系数
  inchars_per_minutes: 20    # 人每分钟输入20个字
  lines_per_minutes: 2       # 人每分钟输入2行代码
  min_minutes: 5             # 最小分钟数

task_dir: "/mnt/prod_env/user-indicator/raw/task"
repo_dir: "/mnt/prod_env/user-indicator/raw/repo"
analysed_dir: "./analysed"
org_csv_file: "./analysed/org_mapping.csv"
org_dsn: "host=10.72.10.64 port=25432 user=costrict_reader password=hello_costrict sslmode=disable"
# HTTP 代理（用于 git clone 等网络操作）
http_proxy: "http://127.0.0.1:7890"

traditional_dev_lines_per_day: 100
silica_max_days: 7

serve:
  port: 8080
  crontab:
    - schedule: "0 0 * * * *"
      command: import-task
      params:
        force: false
    - schedule: "0 5 * * * *"
      command: import-repo
      params:
        force: false
    - schedule: "0 10 * * * *"
      command: silica
      params:
        force: false
    - schedule: "0 15 * * * *"
      command: efficiency
