global:
  imageRegistry: ""
  imagePullSecrets: []
  timezone: Asia/Shanghai

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 250m

backend:
  host: "server"
  port: 9990

persistence:
  enabled: false
  pvcName: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeSelector: {}

tolerations: []

affinity: {}
