
stat_database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: "1"
  dbname: costrict_stat
  sslmode: disable

model_prices:
  GLM-4.7:
    in_price: 0.5
    out_price: 1.0
  GLM-5:
    in_price: 1.0
    out_price: 2.0
  Kimi-K2.5-Moonshot:
    in_price: 1.0
    out_price: 2.0
  MiniMax-M2.1:
    in_price: 0.5
    out_price: 1.0
  Auto:
    in_price: 0.0
    out_price: 0.0

task_dir: "/app/task"
repo_dir: "/app/repo"
analysed_dir: "/app/analysed"
org_csv_file: "/app/analysed/org_mapping.csv"
org_dsn: "host=10.72.10.64 port=25432 user=costrict_reader password=hello_costrict sslmode=disable"
# HTTP 代理（用于 git clone 等网络操作）
http_proxy: "http://127.0.0.1:7890"

traditional_dev_lines_per_day: 100

serve:
  port: 8080
  crontab:
    - schedule: "0 0 * * * *"
      command: import-task
      params:
        force: false
    - schedule: "0 5 * * * *"
      command: import-repo
      params:
        force: false
    - schedule: "0 10 * * * *"
      command: silica
      params:
        force: false
    - schedule: "0 15 * * * *"
      command: efficiency

# 算法估时配置
algo_estimation:
  max_input_chars: 300000    # 最大输入字符数
  max_ratio: 50              # 工作量的最大倍数
  max_factor: 1.0            # 最大的加权系数
  min_factor: 0.2            # 最小的加权系数
  inchars_per_minutes: 20    # 人每分钟输入20个字
  lines_per_minutes: 2       # 人每分钟输入2行代码
  min_minutes: 5             # 最小分钟数
