{{- if .Values.volumes.analysedDir.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kbcli.fullname" . }}-analysed
  labels:
    {{- include "kbcli.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.volumes.analysedDir.pvc.accessMode }}
  {{- if .Values.volumes.analysedDir.pvc.storageClass }}
  storageClassName: {{ .Values.volumes.analysedDir.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.analysedDir.pvc.size }}
{{- end }}
