FROM golang:1.26.0 AS builder
ARG TARGETOS
ARG TARGETARCH
ARG VERSION=v1.0.1
WORKDIR /app

COPY ./core /app/core
COPY ./kbcli/go.mod ./kbcli/go.sum /app/kbcli/

RUN go env -w CGO_ENABLED=0 && \
    go env -w GO111MODULE=on && \
    go env -w GOPROXY=http://mirrors.sangfor.org/nexus/repository/go-proxy-group,direct
RUN cd ./kbcli && go mod download

COPY ./kbcli /app/kbcli

RUN cd /app/kbcli && \
    CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-s -w -X 'main.SoftwareVer=${VERSION}'" -o /app/bin/kbcli *.go && \
    chmod 755 /app/bin/kbcli

RUN chmod +x /app/kbcli/scripts/*.sh

FROM alpine:3.21 AS runtime

ENV env prod
ENV TZ Asia/Shanghai
WORKDIR /app

# 安装cron和必要的工具
RUN sed -i 's|dl-cdn.alpinelinux.org|mirrors.sangfor.com/nexus/repository|g' /etc/apk/repositories
RUN apk add --no-cache dcron tzdata
COPY --from=builder /app/bin/kbcli /app/bin/kbcli
COPY --from=builder /app/kbcli/scripts /app/scripts

ENTRYPOINT ["/app/scripts/docker-entrypoint.sh"]
