package main

import (
	"testing"
	"time"
)

func TestMatchTasksToCommits_TimeWindowMatch(t *testing.T) {
	// 创建临时 CSV
	csv := "user_id,user_name,org1,org2,org3,org4,git_user_name,git_user_email\nuser-001,alice,A,B,C,D,testuser,test@example.com\n"
	path := writeTestCSV(t, csv)
	orgProvider, err := NewOrgProvider(path)
	if err != nil {
		t.Fatalf("创建 OrgProvider 失败: %v", err)
	}

	tasks := []TaskContentFile{
		{
			TaskID:    "task-1",
			UserID:    "user-001",
			StartTime: "2026-03-10T10:00:00Z",
			EndTime:   "2026-03-10T18:00:00Z",
		},
		{
			TaskID:    "task-2",
			UserID:    "user-001",
			StartTime: "2026-03-15T10:00:00Z",
			EndTime:   "2026-03-15T18:00:00Z",
		},
	}

	commits := []CommitDetail{
		{
			Hash:         "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
			AuthorName:   "testuser",
			AuthorEmail:  "test@example.com",
			Timestamp:    time.Date(2026, 3, 10, 14, 0, 0, 0, time.UTC),
			Message:      "feat: add feature",
			LinesAdded:   10,
			LinesDeleted: 2,
		},
		{
			Hash:         "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
			AuthorName:   "testuser",
			AuthorEmail:  "test@example.com",
			Timestamp:    time.Date(2026, 3, 15, 14, 0, 0, 0, time.UTC),
			Message:      "fix: bug fix",
			LinesAdded:   5,
			LinesDeleted: 1,
		},
	}

	matches, classifications := MatchTasksToCommits(commits, tasks, orgProvider)

	// 验证 matches
	if len(matches) < 2 {
		t.Fatalf("期望至少 2 个 match, 实际 %d", len(matches))
	}

	// 验证 classifications 全部为 ai_current
	for _, cls := range classifications {
		if cls.CodeSource != CodeSourceAICurrent {
			t.Errorf("commit %s 期望 ai_current, 实际 %s", cls.CommitHash[:8], cls.CodeSource)
		}
	}
}

func TestMatchTasksToCommits_FileIntersectionScore(t *testing.T) {
	csv := "user_id,user_name,org1,org2,org3,org4,git_user_name,git_user_email\nuser-001,alice,A,B,C,D,testuser,test@example.com\n"
	path := writeTestCSV(t, csv)
	orgProvider, err := NewOrgProvider(path)
	if err != nil {
		t.Fatalf("创建 OrgProvider 失败: %v", err)
	}

	tasks := []TaskContentFile{
		{
			TaskID:    "task-1",
			UserID:    "user-001",
			StartTime: "2026-03-10T10:00:00Z",
			EndTime:   "2026-03-10T18:00:00Z",
			Conversations: []ConversationEntry{
				{
					CodeOutputs: []CodeOutput{
						{Path: "a.go", Code: "package main"},
						{Path: "c.go", Code: "package util"},
					},
				},
			},
		},
	}

	commits := []CommitDetail{
		{
			Hash:         "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
			AuthorName:   "testuser",
			AuthorEmail:  "test@example.com",
			Timestamp:    time.Date(2026, 3, 10, 14, 0, 0, 0, time.UTC),
			Message:      "update files",
			FilesChanged: []string{"a.go", "b.go"},
			LinesAdded:   10,
		},
	}

	matches, _ := MatchTasksToCommits(commits, tasks, orgProvider)

	found := false
	for _, m := range matches {
		if m.TaskID == "task-1" && m.CommitHash == "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" {
			found = true
			// 交集 = {a.go} = 1, max(commit文件数=2, task文件数=2) = 2, 得分 = 0.5
			if m.MatchScore < 0.49 || m.MatchScore > 0.51 {
				t.Errorf("期望 MatchScore ≈ 0.5, 实际 %.2f", m.MatchScore)
			}
			if m.MatchReason != "时间窗口+文件路径匹配" {
				t.Errorf("期望 MatchReason='时间窗口+文件路径匹配', 实际 '%s'", m.MatchReason)
			}
		}
	}
	if !found {
		t.Error("未找到 task-1 和 commit aaa 的匹配")
	}
}

func TestMatchTasksToCommits_UnmappedAuthor(t *testing.T) {
	csv := "user_id,user_name,org1,org2,org3,org4,git_user_name,git_user_email\nuser-001,alice,A,B,C,D,testuser,test@example.com\n"
	path := writeTestCSV(t, csv)
	orgProvider, err := NewOrgProvider(path)
	if err != nil {
		t.Fatalf("创建 OrgProvider 失败: %v", err)
	}

	commits := []CommitDetail{
		{
			Hash:        "cccccccccccccccccccccccccccccccccccccccc",
			AuthorName:  "unknown-dev",
			AuthorEmail: "unknown@other.com",
			Timestamp:   time.Date(2026, 3, 10, 14, 0, 0, 0, time.UTC),
			Message:     "Generated by AI assistant",
			LinesAdded:  20,
		},
		{
			Hash:        "dddddddddddddddddddddddddddddddddddddd",
			AuthorName:  "another-dev",
			AuthorEmail: "another@other.com",
			Timestamp:   time.Date(2026, 3, 10, 15, 0, 0, 0, time.UTC),
			Message:     "fix bug in parser",
			LinesAdded:  5,
		},
	}

	tasks := []TaskContentFile{
		{
			TaskID:    "task-1",
			UserID:    "user-001",
			StartTime: "2026-03-10T10:00:00Z",
			EndTime:   "2026-03-10T18:00:00Z",
		},
	}

	_, classifications := MatchTasksToCommits(commits, tasks, orgProvider)

	for _, cls := range classifications {
		if cls.CommitHash == "cccccccccccccccccccccccccccccccccccccccc" {
			if cls.CodeSource != CodeSourceAIOther {
				t.Errorf("AI message commit 期望 ai_other, 实际 %s", cls.CodeSource)
			}
		}
		if cls.CommitHash == "dddddddddddddddddddddddddddddddddddddd" {
			if cls.CodeSource != CodeSourceUnknown {
				t.Errorf("普通 message commit 期望 unknown, 实际 %s", cls.CodeSource)
			}
		}
	}
}

func TestMatchTasksToCommits_EmptyTasks(t *testing.T) {
	csv := "user_id,user_name,org1,org2,org3,org4,git_user_name,git_user_email\nuser-001,alice,A,B,C,D,testuser,test@example.com\n"
	path := writeTestCSV(t, csv)
	orgProvider, err := NewOrgProvider(path)
	if err != nil {
		t.Fatalf("创建 OrgProvider 失败: %v", err)
	}

	commits := []CommitDetail{
		{
			Hash:        "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
			AuthorName:  "testuser",
			AuthorEmail: "test@example.com",
			Timestamp:   time.Date(2026, 3, 10, 14, 0, 0, 0, time.UTC),
			Message:     "refactor code",
			LinesAdded:  15,
		},
		{
			Hash:        "ffffffffffffffffffffffffffffffffffffffff",
			AuthorName:  "external-dev",
			AuthorEmail: "ext@other.com",
			Timestamp:   time.Date(2026, 3, 10, 15, 0, 0, 0, time.UTC),
			Message:     "add docs",
			LinesAdded:  3,
		},
	}

	var emptyTasks []TaskContentFile
	_, classifications := MatchTasksToCommits(commits, emptyTasks, orgProvider)

	for _, cls := range classifications {
		if cls.CommitHash == "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" {
			// 映射成功但无 task → human
			if cls.CodeSource != CodeSourceHuman {
				t.Errorf("mapped user 无 task 期望 human, 实际 %s", cls.CodeSource)
			}
		}
		if cls.CommitHash == "ffffffffffffffffffffffffffffffffffffffff" {
			// 未映射且无 AI 关键词 → unknown
			if cls.CodeSource != CodeSourceUnknown {
				t.Errorf("unmapped user 无 AI 关键词期望 unknown, 实际 %s", cls.CodeSource)
			}
		}
	}
}
